"""add_positions_to_jobs

Revision ID: 20251127_114800
Revises: d1a735887b7e
Create Date: 2025-11-27 11:48:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251127_114800'
down_revision = 'd1a735887b7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('positions', sa.Integer(), nullable=True, default=1))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'positions')
    # ### end Alembic commands ###
