"""Add html_content field to email_queue table

Revision ID: add_html_content_to_email_queue
Revises: 
Create Date: 2025-12-02 12:43:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_html_content_to_email_queue'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_queue', sa.Column('html_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_queue', 'html_content')
    # ### end Alembic commands ###
