"""Add embeddings fields to users and jobs tables

Revision ID: add_embeddings_fields
Revises: d1a735887b7e
Create Date: 2025-11-27 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_embeddings_fields'
down_revision = 'd1a735887b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_embedding', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('job_embedding', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding_updated_at')
    op.drop_column('jobs', 'job_embedding')
    op.drop_column('users', 'embedding_updated_at')
    op.drop_column('users', 'profile_embedding')
    # ### end Alembic commands ###
