"""add_job_details_fields

Revision ID: d1a735887b7e
Revises: 009_add_advertisements_table
Create Date: 2025-11-27 09:11:04.108405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a735887b7e'
down_revision = '009_add_advertisements_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip ALTER COLUMN for SQLite compatibility
    # op.alter_column('admin_messages', 'is_deleted_by_user',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text("'0'"))
    op.add_column('jobs', sa.Column('experience_required', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('qualifications', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('benefits', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'benefits')
    op.drop_column('jobs', 'responsibilities')
    op.drop_column('jobs', 'qualifications')
    op.drop_column('jobs', 'experience_required')
    # Skip ALTER COLUMN for SQLite compatibility
    # op.alter_column('admin_messages', 'is_deleted_by_user',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
